### ISSUE TITLE
Georgian locale

### ISSUE THREAD

**Issue by DanTaiko** [svenfuchs/rails-i18n#570]
Please, get use of Georgian locale:
https://gist.github.com/DanTaiko/3504507d7e0d2647b426

I don't speak Georgian, and couldn't help with further translation.
I've just got the ge.yaml, that will be of use to others.

**Comment by digitalfrost** [comment]
Adding the Georgian ge.yml file provided breaks the tests

```
Failures:

  1) a rails-i18n rails/locale/ge.yml locale file should not have missing particular pluralization keys
     Failure/Error: it { should_not have_missing_particular_pluralization_keys }
     NoMethodError:
       undefined method `plural_rule_names' for nil:NilClass
     # ./spec/unit/matchers/have_missing_particular_pluralization_keys_matcher.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/translation_spec.rb:19:in `block (3 levels) in <top (required)>'

Finished in 5.46 seconds
2126 examples, 1 failure

Failed examples:

rspec ./spec/unit/translation_spec.rb:19 # a rails-i18n rails/locale/ge.yml locale file should not have missing particular pluralization keys
/home/gerald/.rvm/rubies/ruby-2.2.3/bin/ruby -S rspec spec/integration/backend_reload_spec.rb spec/integration/optional_locale_loading_spec.rb spec/integration/pluralization_spec.rb spec/integration/translation_spec.rb spec/integration/transliteration_spec.rb spec/unit/pluralization_spec.rb spec/unit/translation_spec.rb spec/unit/transliteration_spec.rb failed
```

**Comment by digitalfrost** [comment]
Closing since no  fix for broken test, since 1 year ago.

**Comment by webzorg** [comment]
Where should be the plural_rule_names be defined?

**Comment by webzorg** [comment]
I don't understand the test failure.

**Comment by webzorg** [comment]
Ok I figured it out. I am making a PR for a better (more correct) version just now. The error was that the "ge" is not an official locale code. It needed to be "ka".
