### ISSUE TITLE
Tests fail with locale file should not have legacy interpolations

### ISSUE THREAD

**Issue by digitalfrost** [svenfuchs/rails-i18n#867]
```
 1) a rails-i18n rails/locale/te.yml locale file should not have legacy interpolations
     Failure/Error: it { should_not have_legacy_interpolations }

     ArgumentError:
       invalid byte sequence in US-ASCII
     # /usr/local/bundle/gems/i18n-spec-0.6.0/lib/i18n-spec/matchers/have_legacy_interpolations.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/translation_spec.rb:14:in `block (3 levels) in <top (required)>'

Finished in 0.48971 seconds (files took 0.35761 seconds to load)
1835 examples, 1 failure

Failed examples:

rspec './spec/unit/translation_spec.rb[1:5]' # a rails-i18n rails/locale/te.yml locale file should not have legacy interpolations
```

**Comment by digitalfrost** [comment]
To reproduce use Dockerfile from #868 

and 

Build the image:

```
docker build --tag=railsi18n .
```

Run the tests:

```
docker run railsi18n
```

**Comment by digitalfrost** [comment]
Stale ticket
