### ISSUE TITLE
Siberian pluralization warning

### ISSUE THREAD

**Issue by ryanb** [svenfuchs/rails-i18n#965]
Since upgrading to rails-i18n 7.0.1, I see the following warnings when calling `I18n::JS.filtered_translations`.

```
$ rails c
>> I18n::JS.filtered_translations
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rails-i18n-7.0.1/lib/rails_i18n/../../rails/pluralization/sr.rb:4: warning: already initialized constant I18n::Backend::Base::RailsI18n::Pluralization::Serbian::FROM_2_TO_4
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rails-i18n-7.0.1/lib/rails_i18n/../../rails/pluralization/sr.rb:4: warning: previous definition of FROM_2_TO_4 was here
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rails-i18n-7.0.1/lib/rails_i18n/../../rails/pluralization/sr.rb:5: warning: already initialized constant I18n::Backend::Base::RailsI18n::Pluralization::Serbian::FROM_12_TO_14
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rails-i18n-7.0.1/lib/rails_i18n/../../rails/pluralization/sr.rb:5: warning: previous definition of FROM_12_TO_14 was here
```

I assume this is from PR #925. However I'm uncertain why the pluralization files are loaded multiple times. Is that an issue with [i18n-js](https://github.com/fnando/i18n-js)? If so I can post this there instead.

Is anyone else seeing this?

**Comment by pama** [comment]
@ryanb I created a new rails 7 app, with `gem 'rails-i18n', '~> 7.0.1'` and `gem "i18n-js"`, using ruby `3.0.2p107`. I set locale to `:sr`, and I couldn't reproduce that warning on my rails console. Let me know if I need to do something else to see that warning.

**Comment by ryanb** [comment]
@pama Thanks for looking into this.

It sounds like there's something specific in my app causing the double loading. I'll close this for now and will update when/if I find the culprit.

**Comment by nickcampbell18** [comment]
@ryanb I'm seeing the same thing, did you figure out what this was in the end?

**Comment by ryanb** [comment]
@nickcampbell18 I haven't had a chance to look into this yet, but it's on my todo list. 😃

**Comment by nickcampbell18** [comment]
I can help a little, I'm not using `i18n-js` and I still have this issue so that might rule some things out. From a quick glance, I wonder if this is related to changes in Zeitwerk and autoloading in Rails 7? It might be because the Ruby paths are not expanded out - looking at `I18n.load_path` after the gem initializes:

```ruby
[8] pry(main)> I18n.load_path
=> ["GEM_HOME/gems/activesupport-7.0.0/lib/active_support/locale/en.yml",
 "GEM_HOME/gems/activesupport-7.0.0/lib/active_support/locale/en.rb",
 "GEM_HOME/gems/activemodel-7.0.0/lib/active_model/locale/en.yml",
 "GEM_HOME/gems/activerecord-7.0.0/lib/active_record/locale/en.yml",
 "GEM_HOME/gems/actionview-7.0.0/lib/action_view/locale/en.yml",
 "GEM_HOME/gems/i18n-tasks-0.9.37/config/locales/en.yml",
 "GEM_HOME/gems/i18n-tasks-0.9.37/config/locales/ru.yml",
 "GEM_HOME/gems/rails-i18n-7.0.1/lib/rails_i18n/../../rails/locale/af.yml",
 ...,
 "GEM_HOME/gems/rails-i18n-7.0.1/lib/rails_i18n/../../rails/pluralization/sr.rb",
 ...
]
```

Perhaps Zeitwerk doesn't think it's loaded `sr.rb`, because it's not using the canonical path but rather a `../../` in the middle of it. I'll have another look tomorrow, maybe we need to `File.expand_path` first to make it canonical and then it won't be loaded twice.

**Comment by pama** [comment]
@nickcampbell18 what should I do to reproduce the issue? I tried a couple of times and couldn't get the error.

**Comment by nickcampbell18** [comment]
I'm not 100% sure, for me it warns on every single test run (not at application boot) so is there maybe some interaction with the Rails class caching in test?

**Comment by ryanb** [comment]
For the record, I'm still on Rails 6.1 so the issue isn't specific to Rails 7.

I suspect an initializer is triggering it in my case.

**Comment by pama** [comment]
Thanks for that. I will try on Rails 6.1

**Comment by ryanb** [comment]
@nickcampbell18 if you add `puts caller` to the top of the `rails-i18n` `sr.rb` file it will print out the stack trace.

Here's mine when I load `rails console`.

```
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:236:in `eval'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:236:in `load_rb'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:226:in `load_file'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:18:in `block in load_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:18:in `each'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:18:in `load_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/simple.rb:79:in `init_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/simple.rb:89:in `lookup'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:32:in `translate'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n.rb:207:in `block in translate'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n.rb:203:in `catch'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n.rb:203:in `translate'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activemodel-6.1.4.4/lib/active_model/translation.rb:67:in `human_attribute_name'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-active_record-0.2.6/lib/adapters/wallaby/active_record/model_decorator/fields_builder.rb:18:in `block in general_fields'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-active_record-0.2.6/lib/adapters/wallaby/active_record/model_decorator/fields_builder.rb:15:in `each'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-active_record-0.2.6/lib/adapters/wallaby/active_record/model_decorator/fields_builder.rb:15:in `each_with_object'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-active_record-0.2.6/lib/adapters/wallaby/active_record/model_decorator/fields_builder.rb:15:in `general_fields'
...
```

The [Wallaby gem](https://github.com/wallaby-rails/wallaby) is a Rails engine that does some eager loading and ends up triggering `I18n.translate` when the Rails app loads which loads the translations.

And here's the stack when I run `I18n::JS.filtered_translations` 

```
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:236:in `eval'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:236:in `load_rb'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:226:in `load_file'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:18:in `block in load_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:18:in `each'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/base.rb:18:in `load_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n/backend/simple.rb:79:in `init_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:179:in `block in translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:178:in `instance_eval'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:178:in `translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:136:in `block in scoped_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:135:in `each'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:135:in `scoped_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:55:in `segment_for_scope'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:66:in `block in configured_segments'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:60:in `each'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:60:in `inject'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:60:in `configured_segments'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:105:in `translation_segments'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:95:in `block in filtered_translations'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:94:in `tap'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-js-3.9.0/lib/i18n/js.rb:94:in `filtered_translations'
(irb):1:in `irb_binding'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/2.7.0/irb/workspace.rb:114:in `eval'
/Users/rbates/.rbenv/versions/2.7.5/lib/ruby/2.7.0/irb/workspace.rb:114:in `evaluate'
...
```

I haven't been able to duplicate this in a fresh Rails app. Still trying.

**Comment by ryanb** [comment]
I'm reopening this PR since I'm not the only one with the warning.

**Comment by ryanb** [comment]
@pama @nickcampbell18 

This appears to only happen when translations are loaded when the Rails app is initialized. For some reason `i18n` gem forgets the translations have already been loaded and reloads them when calling `translate` after the Rails app has finished loading.

Here are steps to reproduce the warning in a fresh Rails app, both Rails 6 and Rails 7.

```bash
rails new test-i18n
cd test-i18n
bundle add rails-i18n
echo "I18n.t('hello')" > config/initializers/hello.rb
rails console
>> I18n.t('hello')
# shows warning
```

**Comment by dougedey-shopify** [comment]
The fix in https://github.com/svenfuchs/rails-i18n/pull/972 works for me locally in our apps, so I hope it's the best solution here.

**Comment by MoskitoHero** [comment]
I believe @dougedey-shopify's #972 solution is better than mine since it is more than just a patch and seems to follow the same pattern as other pluralization rules.

**Comment by ryanb** [comment]
PR #972 resolves this for me as well. Thanks!

**Comment by pama** [comment]
@francois-ferrandis you will need to point to master, we didn't launch a new version yet. 😳

**Comment by ryanb** [comment]
Is there anything we can help with that's blocking a new release? Would be nice to get this released.

**Comment by pama** [comment]
I should be able to do it today or tomorrow morning. 🤞
